name: Google Assistant Proxy
version: 0.0.19
slug: google_assistant_proxy
description: "Google Assistant Proxy for Home Assistant allowign to proxy request to Google Assistant"
url: https://github.com/nicoinch/hassio-addons/tree/master/hassio-addon-google-assistant-proxy
init: false
hassio_api: true
hassio_role: default
homeassistant_api: true
ports:
  8085/tcp: 8085
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  jsonKeyFile: your-json-key-file
  tokens: oauth2-token
  language: en-US
schema:
  jsonKeyFile: match(.*)
  tokens: match(.*)
  language: match(.*)
