name: Bard
version: 0.0.5
slug: bard
description: "Bard integration for Home Assistant"
url: https://github.com/nicoinch/hassio-addons/tree/master/hassio-addon-bard
init: false
hassio_api: true
hassio_role: default
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  cookieKey: Value of the cookie named "__Secure-1PSID" from the bard web interface
schema:
  cookieKey: match(.*)