name: Enedis Power Cut
version: 0.0.24
slug: enedis_power_cut
description: "Enedis power cut forecasts integration for Home Assistant"
url: https://github.com/nicoinch/hassio-addons/tree/master/hassio-addon-enedis-power-cut
init: false
hassio_api: true
hassio_role: default
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
